name: Build Runner AMI

on:
  push:
    branches: [main]
    paths: ['packer/**']
  schedule:
    - cron: '0 3 * * 0' # Every Sunday at 3:00 AM
  workflow_dispatch:
    inputs:
      runner_version:
        description: 'GitHub runner version'
        default: '2.320.0'

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-west-2
      - uses: hashicorp/setup-packer@main
        with:
          version: "1.10.0"
      - name: Build AMI
        working-directory: packer
        run: |
          packer init github-runner.pkr.hcl
          packer build -var "runner_version=${{ inputs.runner_version || '2.320.0' }}" github-runner.pkr.hcl
